name: map_and_localization
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  http: ^1.5.0
  provider: ^6.1.5+1
  google_maps_flutter: ^2.13.1  
  google_maps_flutter_web: ^0.5.14+2
  go_router: ^16.3.0
  location: ^8.0.1
  geocoding: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.10.1
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true
